# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5e46a5b0e56fad43ca861987c56a791777b56991506d765adf31d96fc390df677170cdf44750aa5d562595520c5dd4a59e7407cebcce57538be63ad6245b95c

test:
  secret_key_base: c7cdc905d02a6bec4621d4da57707c78b190b19c9733e4b2dac7ee5bff872230acc985d3d93261dd7713482efd7b64dbb1d4d75b65b54749ac64ac7925386260

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
